//
//  DragonStruct.swift
//  MythWorks
//
//  Created by Masimo Stephenson on 12/4/25.
//

import Foundation

struct Dragon: Identifiable, Hashable {
    var id = UUID()
    var image: String
    let name: String
    let species: String
    let lore: String
    let fireRating: Int
    let weaknesses: [String]
    let abilities: [String]
    
    static let dragons: [Dragon] = [
        Dragon(image: "FireDragon", name: "Pyrescale Ravager", species: "Volcanic Drake", lore: "Pyrescale Ravagers are born during violent volcanic eruptions, taking shape from molten rock before the magma even cools. Ancient legends say they are the “anger” of the earth itself, manifesting whenever the land is threatened. Tribes who live near the Scorched Plains believe that when a Pyrescale emerges, a great territorial shift—earthquake, eruption, or war—is destined to follow. Few have survived witnessing one up close.", fireRating: 9, weaknesses: ["Extreme cold", "obsidian-tipped weapons"], abilities: ["Lava breath", "molten armor skin", "creates localized earthquakes"]),
        Dragon(image: "CrystalDragon", name: "Frostmaw Oracle", species: "Crystal Wyvern", lore: "Frostmaw Oracles dwell in glacial caverns where the walls naturally amplify their haunting, harmonic cries. Some believe these cries foretell events, and northern shamans trek across frozen oceans seeking their wisdom. The Oracle’s breath does not merely freeze—it traps visions inside the ice, which melt to reveal omens. Many rulers have risked their lives to gain the Oracle’s counsel, though its prophecies are notoriously cryptic.", fireRating: 2, weaknesses: ["Sonic attacks that shatter its crystal plates"], abilities: ["Predictive vision", "cryo-blast", "ice manipulation"]),
        Dragon(image: "StormDragon", name: "Thundergorge Serpent", species: "Storm Serpent Dragon", lore: "Said to be the first creature born when the world’s skies split open, the Thundergorge Serpent coils eternally within storm fronts. Sailors consider it the bringer of righteous storms that punish the arrogant. When it hunts, an entire region may suffer endless thunder for days. Early civilizations carved its likeness into totems to ensure safe travel—but if the Serpent becomes angered, no prayer can quiet the sky.", fireRating: 5, weaknesses: ["Grounding chains", "metal nets"], abilities: ["Lightning breath", "storm summoning", "electrical invisibility"]),
        Dragon(image: "ForestDragon", name: "Verdant Spineback", species: "Forest Guardian Dragon", lore: "Verdant Spinebacks have existed since the first forests took root. Their spines sprout living vines and moss that shift with the seasons. When one dies, an entire grove grows from its resting place—creating sacred “Dragon Forests” protected by druidic circles for millennia. Hunters once tried to capture a Spineback for its regenerative sap, but doing so caused the forest around them to rise and swallow them whole.", fireRating: 4, weaknesses: ["Fire", "toxins"], abilities: ["Regeneration", "plant control", "camouflage"]),
        Dragon(image: "CelestialDragon", name: "Aetherflare Warden", species: "Celestial Dragon", lore: "These dragons drift between the upper atmosphere and the edge of the astral realm. Ancient murals describe them as emissaries from the “Star Courts,” guardians who prevent cosmic anomalies from crashing into the mortal world. Occasionally, one descends to bless a chosen champion with radiant magic. However, there are also tales of Wardens extinguishing entire civilizations when they tampered with forbidden cosmic energies.", fireRating: 8, weaknesses: ["Dark magic", "corrupted mana"], abilities: ["Gravity manipulation", "radiant fire", "flight without wings"]),
        Dragon(image: "EarthDragon", name: "Ironjaw Burrower", species: "Subterranean Drake", lore: "Ironjaws carve tunnels beneath mountains so vast that entire cave systems are built from their abandoned burrows. Dwarves once revered them as earth spirits until a catastrophic burrowing collapsed a fortified citadel. Since then, Ironjaws are considered a bad omen: a sign that the mountain is shifting or a great mineral vein is about to rupture. Some prospectors still follow their rumbling trails, believing where an Ironjaw goes, treasure lies deeper.", fireRating: 6, weaknesses: ["Light blindness", "flammable gas pockets"], abilities: ["Rock-chewing jaws", "seismic pulses", "underground ambush"]),
        Dragon(image: "IllusionDragon", name: "Emberveil Mirage Dragon", species: "Illusionfire Dragon", lore: "Emberveils live in deserts where heat distortions blur the horizon. Their shimmering forms are often mistaken for mirages, and many travelers die chasing illusions meant to distract predators from the dragon’s true location. Ancient illusionists sought to bond with these creatures to gain their power, but no mortal mind could withstand the constant shifting of reality around them. Some say an Emberveil’s illusions become more real the longer you’re trapped inside them.", fireRating: 7, weaknesses: ["Direct physical hits break its illusions"], abilities: ["Illusion casting", "invisibility", "confusion breath"]),
        Dragon(image: "OceanicDragon", name: "Bloodtide Leviadrake", species: "Oceanic Dragon", lore: "When a Bloodtide rises from the deep, entire ecosystems shift. The glowing crimson tide that accompanies it is not blood, but a bioluminescent bloom that feeds on the dragon’s shifting aura. Sailors claim the Leviadrake judges the worthiness of vessels—it spares humble fishing ships but drags imperial warships into the abyss. Some coastal cities secretly worship it as a guardian of the sea’s balance.", fireRating: 0, weaknesses: ["Desiccation", "extreme heat"], abilities: ["Tidal wave creation", "water pressure blasts", "sonic roar underwater"]),
        Dragon(image: "ShadowDragon", name: "Gloomshroud Nightreaver", species: "Shadow Dragon", lore: "Legends tell of a fortress swallowed by darkness when its king made a pact with a Nightreaver. These dragons feed on fear, drawing power from nightmares to shape living shadows. They rarely attack directly; instead, they send phantom claws or whisper terrifying visions into sleeping minds. Wherever a Nightreaver settles, light sources grow faint and hope slowly erodes. Entire armies have fled empty battlefields after hearing its unearthly growl.", fireRating: 3, weaknesses: ["Bright light", "holy relics"], abilities: ["Shadow teleportation", "fear aura", "darkness manipulation"]),
        Dragon(image: "SolarDragon", name: "Suncrest Herald", species: "Solar Drake", lore: "Suncrests are revered as symbols of rebirth. They emerge only during the first sunrise after an age-ending catastrophe—war, plague, or natural disaster. Their wings scatter shimmering “sun motes” that heal the land and ignite courage in mortal hearts. However, their presence also foreshadows great trials ahead; the brighter the Herald burns, the greater the coming conflict. Prophets say a Herald never appears without purpose.", fireRating: 10, weaknesses: ["Lunar eclipses suppress its power"], abilities: ["Solar beam breath", "heat barrier", "healing flame"])
    ]
}
